stages:
- name: Build & Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/pilot:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: docker.pkg.github.com
timeout: 60
notification:
  recipients:
  - recipient: '#homelab-development'
    notifier: c-m8vp6:n-z5t47
  condition:
  - Success
  - Changed
  - Failed
