{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pilot.serviceAccountName" . }}
  labels:
{{ include "pilot.labels" . | indent 4 }}
{{- end -}}
